PATCH http://localhost:3000/profiledetails
Content-Type: application/json

{
  "email" : "toyotalanka@gmail.com",
  "newName": "toyota",
  "newMobile": "0777145124",
  "newProvince": "province",
  "newDistrict": "district"
}

###
POST http://localhost:3000/servicerequest
Content-Type: application/json

{
  "vehicleMake": "toyota",
  "vehicleModel": "corolla",
  "serviceCenter": "Galle center",
  "specificServices": "oil change",
  "dateTime": "02/05/2022",
  "timeSlot" : "1pm-3pm",
  "userEmail": "vima@gmail.com",
  "status" : "pending"
}

###
GET http://localhost:3000/profiledetails


###
GET http://localhost:3000/vehiclemake


